FROM node:18-alpine

WORKDIR /app

# Install updates
RUN apk update && apk upgrade && apk add --no-cache openssl
RUN ln -s /usr/lib/libssl.so.3 /lib/libssl.so.3

# Copy everything
COPY . .

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Build
RUN npm run build

EXPOSE 3000

# Simple start command
CMD ["sh", "-c", "mkdir -p ./prisma/database && npx prisma db push && npm run start"]